//! Loads the versioned cost-model provenance manifest, compiled into the
//! binary via `include_str!` for deterministic, dependency-free access at
//! runtime (WEEK3_COST_CONTRACT.md section 5).
//!
//! Every architecture constant here traces to a hash-verified source file
//! (see `cost_model/README.md`'s provenance chain) -- nothing here is a
//! magic number, it is a parsed, versioned artifact regenerated by
//! `scripts/build_cost_provenance.py`.

use std::sync::OnceLock;

use serde::Deserialize;

const MANIFEST_JSON: &str =
    include_str!("../../../benchmarks/workloads/week3_cost/request_cost_provenance.v1.json");

#[derive(Debug, Deserialize)]
struct SourceProvenance {
    model_id: String,
}

#[derive(Debug, Deserialize)]
struct DerivedArchitecture {
    logical_kv_bytes_per_token: u64,
}

#[derive(Debug, Deserialize)]
struct RawManifest {
    source_provenance: SourceProvenance,
    derived_architecture: DerivedArchitecture,
}

/// The parts of the manifest the runtime cost path actually needs.
///
/// Deliberately narrower than the full manifest schema: everything else
/// (hashes, vLLM version, effective KV dtype) is Week 3 evidence, not a
/// runtime input to the formula itself.
#[derive(Debug, Clone)]
pub struct Provenance {
    pub model_id: String,
    pub logical_kv_bytes_per_token: u64,
}

pub fn provenance() -> &'static Provenance {
    static PROVENANCE: OnceLock<Provenance> = OnceLock::new();
    PROVENANCE.get_or_init(|| {
        let raw: RawManifest = serde_json::from_str(MANIFEST_JSON).unwrap_or_else(|err| {
            panic!(
                "benchmarks/workloads/week3_cost/request_cost_provenance.v1.json is malformed \
                 ({err}) -- regenerate it with scripts/build_cost_provenance.py"
            )
        });
        Provenance {
            model_id: raw.source_provenance.model_id,
            logical_kv_bytes_per_token: raw.derived_architecture.logical_kv_bytes_per_token,
        }
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provenance_matches_the_investigation_report() {
        let p = provenance();
        assert_eq!(p.model_id, "meta-llama/Llama-3.2-3B-Instruct");
        assert_eq!(p.logical_kv_bytes_per_token, 114_688);
    }
}
