"""Only session #2 headline evidence may define the breach (Phase A).

The classifier used to ask "is anything wrong with this record". It now asks
"has this record proven every property of headline evidence", and the
difference is the whole point: the first form passes anything it does not
recognise, and everything dangerous here is something it would not recognise.

What is actually on disk when `resolve_breach` runs, after teardown:

    benchmarks/runs/headline/headline_r1_rps2.metrics.json      <- evidence
    benchmarks/runs/scout/headline_r1_rps2.metrics.json         <- N=500, 1 repeat
    benchmarks/evidence/week2/first_session/*.metrics.json      <- other convention
    benchmarks/runs/secondary/secondary_rps2.metrics.json       <- never headline

The scout file's *name* is indistinguishable from the headline file's, because
both families are generated by the same generator with the same tag scheme.
Directory is not authority, filename is not authority, and `point_state` reads
`UNDER`/`OVER` in every one of them. Only the record's own declaration, checked
field by field against the frozen workload, separates them.

Each rejection test removes exactly ONE property from an otherwise-valid
record, so a passing test cannot be an accident of some other missing field.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from metrics.classification import (
    HeadlineEvidenceSpec,
    NotHeadlineEvidence,
    RepeatPolicy,
    classify_point,
    resolve_breach,
)
from metrics.headline_point import (
    HEADLINE_EVIDENCE,
    HEADLINE_POINT_RECORD_VERSION,
    SCOUT_DIAGNOSTIC,
)

pytestmark = pytest.mark.redesign

REPO_ROOT = Path(__file__).resolve().parents[2]
HEADLINE_MEMBERSHIP = "a49ecdd8071920303f240fcf0b8da42dbbc66da593ae88e3c07aa246c4b5aa7b"
SCOUT_MEMBERSHIP = "e9470f8f85f228358567c61ae4b0b67040942f4858747cc6076ecea94237de67"
N = 4000

SPEC = HeadlineEvidenceSpec(membership_id=HEADLINE_MEMBERSHIP, percentile_population_n=N)
POLICY = RepeatPolicy(min_valid_repeats=1, n_per_run=N, n_max=5000,
                      max_repeats_authorized=3, headline=SPEC)


def _valid(repeat_id: int = 1, state: str = "UNDER", **overrides) -> dict:
    record = {
        "record_version": HEADLINE_POINT_RECORD_VERSION,
        "evidence_class": HEADLINE_EVIDENCE,
        "may_define_headline_breach": True,
        "schedule_scheme_version": "headline-schedule-v2",
        "process_epoch": "vllm-start-1000",
        "percentile_population_n": N,
        "canonical_prompt_membership_id": HEADLINE_MEMBERSHIP,
        "repeat_id": repeat_id,
        "arrival_seed": 20260819000 + repeat_id,
        "assignment_seed": 20260819500 + repeat_id,
        "nominal_lambda_rps": 2.0,
        "point_state": state,
        "point_state_reason": "synthetic",
        "ttft_p99_ms": 410.0 if state == "UNDER" else 610.0,
        "ttft_censoring_rate": 0.0,
        "tail_censoring_warning": False,
        "schedule_delivery_ok": True,
        "exact_n_honoured": True,
    }
    record.update(overrides)
    return record


# ---------------------------------------------------------------------------
# 1. The acceptance case. Without this the rejections prove nothing.
# ---------------------------------------------------------------------------


def test_a_valid_session_2_headline_record_is_accepted():
    assert classify_point([_valid()], POLICY).state == "UNDER"


def test_the_spec_matches_the_frozen_artifacts():
    """`_valid()` is only meaningful if it describes the real workload.

    Reads the frozen files directly rather than trusting the constants above,
    so a regenerated workload or an edited policy fails here instead of
    quietly making every other test in this file test nothing.
    """
    frozen = HeadlineEvidenceSpec.from_frozen()
    assert frozen.membership_id == HEADLINE_MEMBERSHIP
    assert frozen.percentile_population_n == N
    assert frozen.schedule_scheme_version == "headline-schedule-v2"

    workload = json.loads(
        (REPO_ROOT / "benchmarks" / "workloads" / "week2_headline" / "canonical_v1.json")
        .read_text(encoding="utf-8"))
    assert workload["membership_id"] == HEADLINE_MEMBERSHIP


def test_the_production_policy_loads_from_the_frozen_policy_file():
    policy = RepeatPolicy.from_frozen()
    assert policy.min_valid_repeats == 3
    assert policy.require_unanimous is True
    assert policy.n_per_run == N
    assert policy.max_repeats_authorized == 3
    assert policy.headline is not None
    assert policy.headline.membership_id == HEADLINE_MEMBERSHIP


# ---------------------------------------------------------------------------
# 2-6. The required rejections, one missing property at a time.
# ---------------------------------------------------------------------------


def test_control_a_scout_record_is_rejected():
    record = _valid(evidence_class=SCOUT_DIAGNOSTIC, may_define_headline_breach=False)
    with pytest.raises(NotHeadlineEvidence, match="evidence_class"):
        classify_point([record], POLICY)


def test_control_a_missing_evidence_class_is_rejected():
    """Previously this defaulted to headline, on the reasoning that only
    legacy writers omit it. That reasoning is exactly backwards for a gate:
    the default decided the outcome for every artifact the gate had never
    seen."""
    record = _valid()
    del record["evidence_class"]
    with pytest.raises(NotHeadlineEvidence, match="evidence_class=None"):
        classify_point([record], POLICY)


def test_control_an_unknown_evidence_class_is_rejected():
    record = _valid(evidence_class="looks_fine_to_me")
    with pytest.raises(NotHeadlineEvidence, match="evidence_class"):
        classify_point([record], POLICY)


def test_control_a_session_1_legacy_record_is_rejected():
    """A record from the frozen `metrics/point.py`: no record_version, no
    evidence class, a different percentile convention, and `tail_valid`
    instead of the session #2 gates."""
    legacy = {
        "offered_rps": 2.0, "achieved_rps": 1.91, "nominal_lambda_rps": 2.0,
        "repeat_id": 1, "canonical_prompt_membership_id": HEADLINE_MEMBERSHIP,
        "arrival_seed": 1, "assignment_seed": 2,
        "warmup_n_s": 10.0, "window_s": 120.0, "n_samples_window": 248,
        "tail_valid": True, "ttft_p99_ms": 402.0, "point_state": "UNDER",
    }
    with pytest.raises(NotHeadlineEvidence, match="record_version"):
        classify_point([legacy], POLICY)


def test_control_the_scout_workload_cannot_become_headline_evidence_by_being_stamped():
    """The path that would survive every other check.

    Drive a scout schedule through the headline entry point and the record
    gets `evidence_class: headline_evidence` honestly — the driver really was
    the headline driver. What it cannot fake is the workload: the membership
    id and N still belong to the scout family, and that is what is checked.
    """
    stamped = _valid(canonical_prompt_membership_id=SCOUT_MEMBERSHIP,
                     percentile_population_n=500)
    with pytest.raises(NotHeadlineEvidence, match="not the headline workload"):
        classify_point([stamped], POLICY)


def test_control_an_incorrect_headline_membership_is_rejected():
    with pytest.raises(NotHeadlineEvidence, match="not the headline workload"):
        classify_point([_valid(canonical_prompt_membership_id="0" * 64)], POLICY)


def test_control_a_mismatched_schedule_scheme_is_rejected():
    """A legacy v1 schedule driven through a session #2 path: right stamp,
    right workload, wrong measurement contract."""
    with pytest.raises(NotHeadlineEvidence, match="schedule_scheme_version"):
        classify_point([_valid(schedule_scheme_version="loadgen-schedule-v1")], POLICY)


def test_control_a_mismatched_n_is_rejected():
    with pytest.raises(NotHeadlineEvidence, match="percentile_population_n"):
        classify_point([_valid(percentile_population_n=500)], POLICY)


def test_control_a_flipped_authority_flag_alone_is_rejected():
    """`evidence_class` and `may_define_headline_breach` are written together
    and checked separately, so hand-editing either one still fails."""
    with pytest.raises(NotHeadlineEvidence, match="may_define_headline_breach"):
        classify_point([_valid(may_define_headline_breach=False)], POLICY)


@pytest.mark.parametrize("gate", ["schedule_delivery_ok", "exact_n_honoured"])
def test_control_an_absent_validity_gate_is_rejected_not_assumed_passing(gate):
    """The fail-open that was there before: `record.get(gate, True)` read a
    gate that was never computed as a gate that passed."""
    record = _valid()
    del record[gate]
    with pytest.raises(NotHeadlineEvidence, match=f"{gate} is absent"):
        classify_point([record], POLICY)


@pytest.mark.parametrize("gate", ["schedule_delivery_ok", "exact_n_honoured"])
def test_a_failed_validity_gate_excludes_rather_than_raises(gate):
    """The deliberate asymmetry.

    Identity and authority are structural: a record that cannot prove what it
    is must not be reasoned about at all. Measurement quality is not — a
    repeat that delivered badly IS headline evidence, it is just evidence that
    this repeat is invalid, and the aggregate has to be able to say
    "2 valid, 1 excluded" rather than refuse to produce a report.
    """
    records = [_valid(1), _valid(2), _valid(3, **{gate: False})]
    aggregate = classify_point(records, RepeatPolicy(
        min_valid_repeats=3, n_per_run=N, n_max=5000, max_repeats_authorized=3,
        headline=SPEC))
    assert len(aggregate.excluded_repeats) == 1
    assert aggregate.state == "UNCERTAIN"


def test_control_a_missing_process_epoch_is_rejected():
    """Lock 3A ("no cross-epoch families") is only enforceable if the record
    says which server process produced it."""
    record = _valid()
    del record["process_epoch"]
    with pytest.raises(NotHeadlineEvidence, match="process_epoch is absent"):
        classify_point([record], POLICY)


def test_control_repeats_from_two_process_epochs_are_refused():
    """The realistic session #2 failure, spelled out in the runbook §7: two
    repeats drive, the spot instance is preempted, vLLM restarts, and the
    third repeat is driven in a fresh process. Every record is honest headline
    evidence -- and combining them puts process-initialization variance into
    exactly one repeat, at the boundary λ, invisibly."""
    records = [_valid(1), _valid(2), _valid(3, process_epoch="vllm-start-9999")]
    with pytest.raises(ValueError, match="process epochs"):
        classify_point(records, RepeatPolicy(min_valid_repeats=3, headline=SPEC))


def test_one_epoch_across_the_family_classifies_normally():
    """The paired positive."""
    records = [_valid(i) for i in (1, 2, 3)]
    assert classify_point(records, RepeatPolicy(
        min_valid_repeats=3, headline=SPEC)).state == "UNDER"


def test_control_an_unstamped_tail_warning_cannot_finalize_a_boundary_point():
    """The remaining `.get(key, falsy)` fail-open.

    A boundary point with 3% censoring and no `tail_censoring_warning` flag
    used to finalize with no review, because `.get()` returned None and None
    is falsy. The warning is now derived from the censoring rate, which the
    gate has already proven is present and numeric.
    """
    records = [_valid(i, state="OVER", ttft_censoring_rate=0.03) for i in (1, 2, 3)]
    for record in records:
        del record["tail_censoring_warning"]

    policy = RepeatPolicy(min_valid_repeats=3, headline=SPEC)
    assert classify_point(records, policy, boundary_determining=False).state == "OVER"
    aggregate = classify_point(records, policy, boundary_determining=True)
    assert aggregate.state == "UNCERTAIN"
    assert aggregate.pending_tail_reviews == [1, 2, 3]


def test_a_completed_review_still_lets_a_boundary_point_finalize():
    """The paired positive: the derived warning must not make the review
    impossible to satisfy."""
    records = [_valid(i, state="OVER", ttft_censoring_rate=0.03,
                      tail_censoring_review_status="COMPLETE") for i in (1, 2, 3)]
    assert classify_point(records, RepeatPolicy(min_valid_repeats=3, headline=SPEC),
                          boundary_determining=True).state == "OVER"


def test_control_a_mis_keyed_lambda_is_refused_by_resolve_breach():
    """`records_by_lambda` is assembled by hand after teardown -- there is no
    loader for it -- and the breach interval is reported at the KEY. A
    mis-keyed entry would publish a λ nothing was measured at."""
    sweep = {1.5: [_valid(1)], 9.9: [_valid(2, state="OVER")]}  # record says 2.0
    with pytest.raises(ValueError, match="mis-keyed"):
        resolve_breach(sweep, POLICY)


def test_control_a_policy_without_a_headline_spec_cannot_classify():
    """A policy that never said which workload is the headline cannot verify
    that a record belongs to it, so it refuses rather than skipping the
    check."""
    with pytest.raises(NotHeadlineEvidence, match="states no headline evidence spec"):
        classify_point([_valid()], RepeatPolicy())


def test_the_sweep_level_entry_point_is_gated_too():
    """`resolve_breach` is the function the session actually calls. Gating
    only `classify_point` would leave the real entry point open if the two
    ever stopped sharing a path."""
    sweep = {
        2.0: [_valid(1, nominal_lambda_rps=2.0)],
        2.5: [_valid(2, state="OVER", nominal_lambda_rps=2.5)],
        3.0: [_valid(3, nominal_lambda_rps=3.0, evidence_class=SCOUT_DIAGNOSTIC)],
    }
    with pytest.raises(NotHeadlineEvidence):
        resolve_breach(sweep, POLICY)


def test_rejected_records_are_still_readable_as_data():
    """Rejection is about eligibility, not legibility. Session #1's artifacts
    and the scout family stay readable through their own paths -- this gate
    only decides what may define the breach."""
    scout = _valid(evidence_class=SCOUT_DIAGNOSTIC, may_define_headline_breach=False)
    assert scout["ttft_p99_ms"] == 410.0
    assert scout["point_state"] == "UNDER"
